[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"

# Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# EVM version
evm_version = "shanghai"

# Gas limit for tests
gas_limit = 9223372036854775807

# RPC endpoints
[rpc_endpoints]
kaia_kairos = "https://public-en-kairos.node.kaia.io"
kaia_mainnet = "https://public-en.node.kaia.io"

# Etherscan API keys (for verification)
[etherscan]
kaia_kairos = { key = "${KAIASCAN_API_KEY}", url = "https://kairos.kaiascan.io/api" }
kaia_mainnet = { key = "${KAIASCAN_API_KEY}", url = "https://kaiascan.io/api" }

# Formatter settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
